### ISSUE TITLE
"Guideline 3.5 Make interactive elements distinguishable" more suited to COGA/LowVis?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/Mobile-A11y-Extension#1]
Looking at https://w3c.github.io/Mobile-A11y-Extension/ the (then) proposed

> Guideline 3.5 Make interactive elements distinguishable
> 
> 3.5.1 Triggers Distinguishable: Elements that trigger changes should be sufficiently distinct to be clearly distinguishable from non-actionable elements (content, status information, etc). [MOBILE]

seems more suited to the task forces tackling cognitive and/or low vision. suggest removing this from the mobile TF proposals

**Comment by patrickhlauke** [comment]
looking at http://w3c.github.io/coga/gap-analysis/#issues-with-flat-design it seems there is indeed overlap with what COGA want to tackle. therefore i'd advise that we drop this from our workload.

**Comment by kwahlbin** [comment]
Cognitive taskforce will be taking the lead on this
